#!/usr/bin/env node
/**
 * Fetch the unfoldingWord cover logos from the CDN and bundle them into the
 * package as inline data URIs, so PDF/HTML rendering never has to fetch them at
 * render time (important on slow/unreliable networks).
 *
 * Output: src/assets/logos.generated.js  (committed — re-run to refresh)
 * Usage:  npm run fetch-logos
 */
import { writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const CDN_BASE = 'https://cdn.door43.org/assets/uw-icons';

// Every logo the print assembler can reference (default + per-resource).
const LOGO_FILES = [
  'uW-app-256.png',
  'logo-uta-256.png',
  'logo-utn-256.png',
  'logo-utq-256.png',
  'logo-utw-256.png',
  'logo-ult-256.png',
  'logo-ust-256.png',
  'logo-obs-256.png',
];

const here = dirname(fileURLToPath(import.meta.url));
const outDir = join(here, '..', 'src', 'assets');
const outFile = join(outDir, 'logos.generated.js');

async function fetchLogo(file) {
  const url = `${CDN_BASE}/${file}`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${file}: HTTP ${res.status}`);
  const buf = Buffer.from(await res.arrayBuffer());
  const type = res.headers.get('content-type') || 'image/png';
  return `data:${type};base64,${buf.toString('base64')}`;
}

async function main() {
  console.error(`Fetching ${LOGO_FILES.length} logos from ${CDN_BASE} ...`);
  const entries = {};
  for (const file of LOGO_FILES) {
    entries[file] = await fetchLogo(file);
    console.error(`  ✓ ${file} (${entries[file].length} chars)`);
  }

  const body =
    '// AUTO-GENERATED by scripts/fetch-logos.mjs — do not edit by hand.\n' +
    '// Run `npm run fetch-logos` to refresh from ' +
    CDN_BASE +
    '\n/* eslint-disable */\n' +
    'export const LOGO_DATA_URIS = ' +
    JSON.stringify(entries, null, 2) +
    ';\n';

  await mkdir(outDir, { recursive: true });
  await writeFile(outFile, body, 'utf8');
  console.error(`Wrote ${outFile}`);
}

main().catch((err) => {
  console.error(`fetch-logos failed: ${err.message}`);
  process.exit(1);
});
