/**
 * Bible book data with testament information
 * Contains all 66 canonical Bible books with their identifiers, titles, USFM codes, and testament classification
 */
export const BibleBookData = {
  gen: { id: 'gen', title: 'Genesis', usfm: '01-GEN', testament: 'old' },
  exo: { id: 'exo', title: 'Exodus', usfm: '02-EXO', testament: 'old' },
  lev: { id: 'lev', title: 'Leviticus', usfm: '03-LEV', testament: 'old' },
  num: { id: 'num', title: 'Numbers', usfm: '04-NUM', testament: 'old' },
  deu: { id: 'deu', title: 'Deuteronomy', usfm: '05-DEU', testament: 'old' },
  jos: { id: 'jos', title: 'Joshua', usfm: '06-JOS', testament: 'old' },
  jdg: { id: 'jdg', title: 'Judges', usfm: '07-JDG', testament: 'old' },
  rut: { id: 'rut', title: 'Ruth', usfm: '08-RUT', testament: 'old' },
  '1sa': { id: '1sa', title: '1 Samuel', usfm: '09-1SA', testament: 'old' },
  '2sa': { id: '2sa', title: '2 Samuel', usfm: '10-2SA', testament: 'old' },
  '1ki': { id: '1ki', title: '1 Kings', usfm: '11-1KI', testament: 'old' },
  '2ki': { id: '2ki', title: '2 Kings', usfm: '12-2KI', testament: 'old' },
  '1ch': { id: '1ch', title: '1 Chronicles', usfm: '13-1CH', testament: 'old' },
  '2ch': { id: '2ch', title: '2 Chronicles', usfm: '14-2CH', testament: 'old' },
  ezr: { id: 'ezr', title: 'Ezra', usfm: '15-EZR', testament: 'old' },
  neh: { id: 'neh', title: 'Nehemiah', usfm: '16-NEH', testament: 'old' },
  est: { id: 'est', title: 'Esther', usfm: '17-EST', testament: 'old' },
  job: { id: 'job', title: 'Job', usfm: '18-JOB', testament: 'old' },
  psa: { id: 'psa', title: 'Psalms', usfm: '19-PSA', testament: 'old' },
  pro: { id: 'pro', title: 'Proverbs', usfm: '20-PRO', testament: 'old' },
  ecc: { id: 'ecc', title: 'Ecclesiastes', usfm: '21-ECC', testament: 'old' },
  sng: { id: 'sng', title: 'Song of Songs', usfm: '22-SNG', testament: 'old' },
  isa: { id: 'isa', title: 'Isaiah', usfm: '23-ISA', testament: 'old' },
  jer: { id: 'jer', title: 'Jeremiah', usfm: '24-JER', testament: 'old' },
  lam: { id: 'lam', title: 'Lamentations', usfm: '25-LAM', testament: 'old' },
  ezk: { id: 'ezk', title: 'Ezekiel', usfm: '26-EZK', testament: 'old' },
  dan: { id: 'dan', title: 'Daniel', usfm: '27-DAN', testament: 'old' },
  hos: { id: 'hos', title: 'Hosea', usfm: '28-HOS', testament: 'old' },
  jol: { id: 'jol', title: 'Joel', usfm: '29-JOL', testament: 'old' },
  amo: { id: 'amo', title: 'Amos', usfm: '30-AMO', testament: 'old' },
  oba: { id: 'oba', title: 'Obadiah', usfm: '31-OBA', testament: 'old' },
  jon: { id: 'jon', title: 'Jonah', usfm: '32-JON', testament: 'old' },
  mic: { id: 'mic', title: 'Micah', usfm: '33-MIC', testament: 'old' },
  nam: { id: 'nam', title: 'Nahum', usfm: '34-NAM', testament: 'old' },
  hab: { id: 'hab', title: 'Habakkuk', usfm: '35-HAB', testament: 'old' },
  zep: { id: 'zep', title: 'Zephaniah', usfm: '36-ZEP', testament: 'old' },
  hag: { id: 'hag', title: 'Haggai', usfm: '37-HAG', testament: 'old' },
  zec: { id: 'zec', title: 'Zechariah', usfm: '38-ZEC', testament: 'old' },
  mal: { id: 'mal', title: 'Malachi', usfm: '39-MAL', testament: 'old' },
  mat: { id: 'mat', title: 'Matthew', usfm: '41-MAT', testament: 'new' },
  mrk: { id: 'mrk', title: 'Mark', usfm: '42-MRK', testament: 'new' },
  luk: { id: 'luk', title: 'Luke', usfm: '43-LUK', testament: 'new' },
  jhn: { id: 'jhn', title: 'John', usfm: '44-JHN', testament: 'new' },
  act: { id: 'act', title: 'Acts', usfm: '45-ACT', testament: 'new' },
  rom: { id: 'rom', title: 'Romans', usfm: '46-ROM', testament: 'new' },
  '1co': { id: '1co', title: '1 Corinthians', usfm: '47-1CO', testament: 'new' },
  '2co': { id: '2co', title: '2 Corinthians', usfm: '48-2CO', testament: 'new' },
  gal: { id: 'gal', title: 'Galatians', usfm: '49-GAL', testament: 'new' },
  eph: { id: 'eph', title: 'Ephesians', usfm: '50-EPH', testament: 'new' },
  php: { id: 'php', title: 'Philippians', usfm: '51-PHP', testament: 'new' },
  col: { id: 'col', title: 'Colossians', usfm: '52-COL', testament: 'new' },
  '1th': { id: '1th', title: '1 Thessalonians', usfm: '53-1TH', testament: 'new' },
  '2th': { id: '2th', title: '2 Thessalonians', usfm: '54-2TH', testament: 'new' },
  '1ti': { id: '1ti', title: '1 Timothy', usfm: '55-1TI', testament: 'new' },
  '2ti': { id: '2ti', title: '2 Timothy', usfm: '56-2TI', testament: 'new' },
  tit: { id: 'tit', title: 'Titus', usfm: '57-TIT', testament: 'new' },
  phm: { id: 'phm', title: 'Philemon', usfm: '58-PHM', testament: 'new' },
  heb: { id: 'heb', title: 'Hebrews', usfm: '59-HEB', testament: 'new' },
  jas: { id: 'jas', title: 'James', usfm: '60-JAS', testament: 'new' },
  '1pe': { id: '1pe', title: '1 Peter', usfm: '61-1PE', testament: 'new' },
  '2pe': { id: '2pe', title: '2 Peter', usfm: '62-2PE', testament: 'new' },
  '1jn': { id: '1jn', title: '1 John', usfm: '63-1JN', testament: 'new' },
  '2jn': { id: '2jn', title: '2 John', usfm: '64-2JN', testament: 'new' },
  '3jn': { id: '3jn', title: '3 John', usfm: '65-3JN', testament: 'new' },
  jud: { id: 'jud', title: 'Jude', usfm: '66-JUD', testament: 'new' },
  rev: { id: 'rev', title: 'Revelation', usfm: '67-REV', testament: 'new' },
};

/**
 * Maps catalog entry subjects to their required supplementary subjects
 */
export const requiredSubjectsMap = {
  'TSV Translation Notes': [
    'Aligned Bible',
    'Translation Academy',
    'Translation Words',
    'TSV Translation Words Links',
    'Hebrew Old Testament',
    'Greek New Testament',
  ],
  'TSV Study Notes': ['Aligned Bible', 'Hebrew Old Testament', 'Greek New Testament'],
  'TSV Study Questions': ['Aligned Bible', 'Hebrew Old Testament', 'Greek New Testament'],
  'TSV Translation Questions': ['Aligned Bible', 'Hebrew Old Testament', 'Greek New Testament'],
  'TSV Translation Words Links': [
    'Aligned Bible',
    'Hebrew Old Testament',
    'Greek New Testament',
    'Translation Words',
  ],
  'TSV OBS Study Notes': ['Open Bible Stories'],
  'TSV OBS Study Questions': ['Open Bible Stories'],
  'TSV OBS Translation Notes': [
    'Open Bible Stories',
    'TSV OBS Translation Words Links',
    'Translation Academy',
    'Translation Words',
  ],
  'TSV OBS Translation Questions': ['Open Bible Stories'],
};

/**
 * Maps subject names to their repository identifiers for catalog searches
 */
export const subjectIdentifierMap = {
  'Aligned Bible': ['ult', 'ust', 'glt', 'gst'],
  'Hebrew Old Testament': 'unfoldingWord/hbo_uhb',
  'Greek New Testament': 'unfoldingWord/el-x-koine_ugnt',
  'Translation Academy': 'ta',
  'Translation Words': 'tw',
  'TSV Translation Words Links': 'twl',
  'Open Bible Stories': 'obs',
  'TSV OBS Study Questions': 'obs-sq',
  'TSV OBS Study Notes': 'obs-sn',
  'TSV OBS Translation Notes': 'obs-tn',
  'TSV OBS Translation Words Links': 'obs-twl',
};
